- module: psoft
  metricsets: ["stat"]
  enabled: true
  # Duration between each metric capture
  period: 60s
  # target host, not used for psoftbeat
  hosts: ["localhost"]

  # Domain list is the inventory of of peoplesoft instances to monitor.
  # This could be in relative path to the psoftbeat install, or reference
  # an explicit path where the inventory may be on a shared drive.
  # See Documents on format of that file.
  pathInventoryFile: "domainList.csv"

  # JMX will use a java client, need path to an installed java home.
  javaPath: "/usr/lib/jvm/jre-1.8.0"

  # Conntect string to local nailgun service tied to the psoftbeat. 
  # This uses a UNIX socket by default.  
  # Defaults to: "local:/<install-path>/psmetric.socket"
  # For Windows override this with a simple TCP Port
  # Windows example: "localhost:13010"
  # The psoftbeat will automatically use this on the client and nailgun connection.
  #nailgunServerConn: local:/opt/psoftbeat/psmetric.socket
